### PR TITLE
Replace dash - with minus −

### PR DESCRIPTION
**Pull request by Atcold**

### CODE REVIEW

**Comment by Atcold** [comment]
Any update on this?

**Comment by Atcold** [comment]
Thanks for merging!

**Comment by Siedlerchr** [comment]
This is breaking all our tests. https://github.com/JabRef/jabref/pull/8639 
 I would suggest to maybe only replace this in math mode?
Consider an author like: `al-Khw{\\={a}}rizm{\\={i}}` which previously was equal to `al-Khwārizmī` with a normal hyphen-dash (U+002D) and now it would be rendered with a minus sign (U+2212) which is wrong.

**Comment by tomtung** [comment]
Ah good point... Currently we "cheat" by not considering math v.s. non-math mode:
 https://github.com/tomtung/latex2unicode/blob/9500bb2ecb19312f6030c645165fd3b430216870/src/main/scala/com/github/tomtung/latex2unicode/helper/Escape.scala#L12

To do this properly, we need to support parsing for math mode blocks, which is non-trivial. Maybe for now the best thing to do is to leave `-` as-is, and only escaping `\textminus` to the Unicode minus sign?

**Comment by Siedlerchr** [comment]
Yes! I think this would be the easiest solution!

**Pull request merged**
